### ISSUE TITLE
アイテム作成時に小数点設定可能に

### ISSUE THREAD

**Issue by jmin-yu** [to-mo-ki/item_shop#13]
`index.js:1 uncaught at _callee at _callee 
 at contractsSaga 
 at takeEvery 
 at callSendContractTx 
 Error: invalid number value (arg="_price", coderType="uint256", value="0.005")`

**Comment by jmin-yu** [comment]
上記の対応に追加でinputに入力チェックを入れる
・マイナス値
・全角
・number format以外

**Comment by to-mo-ki** [comment]
オークションになったので
アイテム作成時→入札時
