### ISSUE TITLE
replace send with cacheSend as WIP

### ISSUE THREAD

**Issue by jmin-yu** [to-mo-ki/item_shop#2]
https://github.com/to-mo-ki/item_shop/blob/e5d00c88bc5faac1f3f4734d7988619f9216ffb3/client/src/AddItem.js#L17

`contract.methods["mintItem"].cacheSend(value, {` or `contract.methods.mintItem.cacheSend(value`

**Comment by to-mo-ki** [comment]
@jmin-yu 
解決しました．原因はsolidityのバージョンっぽかったです．
