### ISSUE TITLE
truffleのコンパイルについて

### ISSUE THREAD

**Issue by to-mo-ki** [to-mo-ki/item_shop#7]
再コンパイル時うまくいかない
```
Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
> Compiling ./contracts/ItemShop.sol
> Compiling ./contracts/ItemToken.sol
✔ Fetching solc version list from solc-bin. Attempt #1

InternalCompilerError: Compiled contract not found.

Compilation failed. See above.
Truffle v5.1.17 (core: 5.1.17)
Node v10.8.0
```
ただし，`--all`をつけると動く

**Comment by to-mo-ki** [comment]
npmのバージョンをあげてみる

**Comment by jmin-yu** [comment]
先ほど共有したと思いますがnodejsのバージョンを11にアップグレードしてためしてください。

**Comment by to-mo-ki** [comment]
@jmin-yu nodeをv11.0.0にしましたがうまくいきませんでした．
ただ，HelloWorldのプログラムは動いたのでプログラムが悪いのかもしれません．

**Comment by jmin-yu** [comment]
先ほどslackで共有しました。
若し、うまくいかない場合はPullPayment.sol当たりが怪しいので@openzepplin/contracts/utilsにAddress.solがあるのでその中にsendValueがあるからそれをつかえるのもありかもです。
`import "@openzepplin/contracts/utils/Address.sol";

Address.sendValue(address, amount);`
